### PR TITLE
Vieira freebsd

### PR DESCRIPTION
**Pull request by brianmay**
Attempt to fix tests broken in #51.

### CODE REVIEW

**Comment by vieira** [comment]
In FreeBSD the fields sport, dport, rsport, rdport are just u_int16_t, not a union as in OSX.
```
Traceback (most recent call last):
  File "/usr/home/vieira/sshuttle/sshuttle/__main__.py", line 155, in <module>
    result = firewall.main(opt.method, opt.syslog)
  File "/usr/home/vieira/sshuttle/sshuttle/firewall.py", line 218, in main
    if not method.firewall_command(line):
  File "/usr/home/vieira/sshuttle/sshuttle/methods/pf.py", line 280, in firewall_command
    dst = pf_query_nat(*(line[13:].split(',')))
  File "/usr/home/vieira/sshuttle/sshuttle/methods/pf.py", line 133, in pf_query_nat
    pnl.sxport = socket.htons(src_port)
TypeError: expected pf_state_xport instance, got int
```

**Comment by vieira** [comment]
I noticed that with Python 3.5 there seems to be some kind of problem setting the firewall although no errors are reported. Reminded me of #43 as the symptoms are the same, but I see that that one happens with 2.7. It was already happening on #51 but as I tested 2.7 first I did not notice the problem. 2.7 works and sets the anchor and when I ran with 3.5 the anchor was already there so it did not have to add the anchor, which seems to be the problem. I will look into this.

On another note, would it be reasonable to move `osdefs = OsDefs()` somewhere else so it does not get instantiated each time the functions are called? Maybe defining it as a default argument value or as global variable?

**Comment by vieira** [comment]
b55fd5c should fix the problem described on the previous comment.

**Comment by brianmay** [comment]
The reason for putting osdefs into each function call, was so I can monkey patch `os.platform` in the tests and still get correct osdefs values for that platform. Thinking about it some more I might be able to monkey patch the osdefs value instead. So osdefs could be a global variable. Will look at that and your other concerns now.

**Comment by brianmay** [comment]
"In FreeBSD the fields sport, dport, rsport, rdport are just u_int16_t, not a union as in OSX."

Looks like I stuffed up the patch here.

However I am not sure I understand, why not just make them unions anyway (like I did in this change)? That way you can refer to values like `pnl.sxport.port` regardless of if it is darwin or not.

**Comment by brianmay** [comment]
Just pushed some fixes for the issues raised so far.

**Comment by vieira** [comment]
You are right Brian, it can be a union as long as it is 16bits. Sorry for the confusion. The way you defined it works nicely and is cleaner. I tested on FreeBSD 10.2 and OSX 10.11.2 and it is working fine. :+1:

**Comment by brianmay** [comment]
Merged in 11838d65c2e5b48827bef560c793f6667a7d6b22.

**Pull request closed without merging**
