### PR TITLE
transfer work from PR #837

### PR DESCRIPTION
**Pull request by aiur-adept**
see #837 for history, I'm going to use this PR to resolve the merge conflicts.

### CODE REVIEW

**Comment by aiur-adept** [comment]
Fixed the merge conflict, it was super simple thank science

**Comment by aiur-adept** [comment]
@brianmay workflows awaiting approval :)

**Comment by aiur-adept** [comment]
@brianmay I'm not able to understand the way the tests are failing. Could you provide some insight perhaps?

**Comment by brianmay** [comment]
Putting the flush() call into a separate thread makes me a bit nervous. I think it might have non-intended consequences, although not really an expert here.

The test is complaining though because it expects `flush()` to be called, when it isn't. Possibly because the mocks don't work in another thread (not sure here).

**Comment by aiur-adept** [comment]
Nothing wrong with flushing from a thread, it's the same stdout and stderr. But the issue is yeah, doing it this way is nondeterministic so none of the tests which expect deterministic flushing will work. However, this was a valid solution to the original deadlocks as reported in the original comment: https://github.com/sshuttle/sshuttle/pull/837#issue-1560968147

Not sure how to proceed. Perhaps we could relax the test expectation to track flushes precisely, or find another way to avoid the deadlocks.

**Comment by aiur-adept** [comment]
Okay, so having reviewed the original PR comment, I think deadlock 1 doesn't exist. A parent and child both flushing stdout at the same could interleave the data, but it won't lock anything. Thus, we can focus on deadlock 2, which occurs because of trying to move the temp file over the hostwatch file while it's being written. Thankfully this doesn't involve putting flushing into a thread. I'll revert the unneeded parts of this and recommit.

**Comment by aiur-adept** [comment]
@brianmay the flake8 is failing like so:

```
Run flake8 sshuttle tests --count --show-source --statistics
tests/client/test_helpers.py:5:1: F401 'time' imported but unused
import time
^
tests/client/test_helpers.py:43:17: F821 undefined name 'stderr_contents'
    for line in stderr_contents:
                ^
tests/client/test_helpers.py:60:17: F821 undefined name 'stderr_contents'
    for line in stderr_contents:
                ^
tests/client/test_helpers.py:87:17: F821 undefined name 'stderr_contents'
    for line in stderr_contents:
                ^
tests/client/test_helpers.py:[11](https://github.com/sshuttle/sshuttle/actions/runs/10126321713/job/28377350552#step:5:12)4:17: F821 undefined name 'stderr_contents'
    for line in stderr_contents:
                ^
1     F401 'time' imported but unused
4     F821 undefined name 'stderr_contents'
5
Error: Process completed with exit code 1.
```

None of this is from my changes btw.

Now, for solving it, it's simple enough to remove the unused import `time`, but `stderr_contents` is less clear. Why are we using an undefined variable?

**Comment by brianmay** [comment]
Are you up-to-date with the latest main? I don't see anything like that here: https://github.com/sshuttle/sshuttle/blob/master/tests/client/test_helpers.py

**Comment by brianmay** [comment]
On second thoughts it looks like this lines come with this PR.

**Comment by aiur-adept** [comment]
@brianmay that's really weird, you're right. let me try to just merge preferentially from upstream master. This change shouldn't even touch the test file.

**Comment by aiur-adept** [comment]
@brianmay ok, i've reduced this to its mininum. Check the diff to see how it works. We set a dirty flag on the need to write the host cache file instead of writing it immediately, since we can't write while reading or else we end up in a lock.

**Review by brianmay — APPROVED** [review]

**Pull request merged**
