### PR TITLE
Yosemite support

### PR DESCRIPTION
**Pull request by seanzxx**
Apple drops the IPFW from OS X Yosemite.  
shuttle cannot work on OS X Yosemite for this reason. 
I forked the sshuttle/sshuttle and add support for the pf.

### CODE REVIEW

**Comment by brianmay** [comment]
This change looks ok to me, and it looks like it shouldn't have any affect for Linux users, which is also good.

Writing and deleting temporary file to /etc  (/etc/pf-sshuttle.conf) seems a bit dodgy, but that can get updated later if required.

I am going to merge this.

**Comment by thshdw** [comment]
@brianmay @seanzxx 

This is not working for me I get 

```
c : -- ignored: that's my address!
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=505/0)
c :   Ready: 3 r=[5] w=[] x=[]
c : Accept TCP: 172.20.10.7:55470 -> 127.0.0.1:12300.
c : -- ignored: that's my address!
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=505/0)
c :   Ready: 3 r=[7] w=[] x=[]
c : DNS request from ('172.20.10.7', 65117) to None: 62 bytes
c :  > channel=14 cmd=DNS_REQ len=62 (fullness=505)
c : mux wrote: 70/70
c : Waiting: 3 r=[5, 7, 9] w=[] x=[] (fullness=567/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=14 cmd=DNS_REQ len=62
```
Mainly I see ```c : -- ignored: that's my address!```

**Comment by brianmay** [comment]
Unfortunately, I am not able to test OS X stuff, as I don't have OS X. Pull requests to fix this are appreciated :-)

**Comment by thshdw** [comment]
@brianmay have you seen https://github.com/sshuttle/sshuttle/pull/3 and the patch to that here https://github.com/pthrasher/sshuttle/pull/1 

In the mean time I'll fork this and see if I can troubleshoot.
Thanks!

**Comment by seanzxx** [comment]
@thshdw can you tell me your OS X version?  I tested it on 10.10.3 beta3 and beta4. 
I don't have other version in hand.  
It seems the ioctl throws an exception.  
You can try to add debug log in the exception handling.  Thanks a lot.

**Comment by thshdw** [comment]
Hi @seanzxx I have OSX Beta 10.10.3

The command i'm running is ```./sshuttle --dns -vvr myuser@mysshserver.com 0/0```

**Comment by brianmay** [comment]
Oops. I appear to be getting confused with all these merge requests, I hadn't noticed there were two distinct merge requests against this project.

I will comment on #3 there.

This is currently my preferred approach, if it cannot be made to work I will consider reverting it however.

**Comment by thshdw** [comment]
@brianmay Thanks for commenting. I appreciate the OSX attention :smile:

**Comment by seanzxx** [comment]
@thshdw Thanks a lot for providing your command line.  I can reproduce this issue. 
I didn't know sshuttle could work this way. :+1: 
I always ran it like this: sudo ./sshuttle --dns -vvr myuser@mysshserver.com 0/0

Because the client need to access the /dev/pf to get the destination address,  it seems the sudo is required.

**Comment by thshdw** [comment]
@seanzxx Thanks for your prompt response! :smile:

@brianmay what are your thoughts?

**Comment by brianmay** [comment]
I am not a fan of requiring sudo for every connection. However it seems on OSX 10.10 Yosemite the only way to get the destination address is with root access. If so, this seems to be rather poor design decision in OS X.

In theory, it might be possible to do something in the firewall process, I believe already gets runs as root. The client would have to send the firewall a command, which the firewall can lookup as root and return the result. Seems rather complicated way just to get the destination IP address however.

**Comment by thshdw** [comment]
@seanzxx 
If I  ```sudo ./sshuttle --dns -vvr myuser@mydomain@my.public.ip.removed 0/0``` I get the following:
```
Starting sshuttle proxy.
recvmsg socket_ext support enabled.
UDP support requires tproxy; disabling UDP.
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
firewall manager ready method pf.
c : connecting to server...
c : executing: ['ssh', 'myuser@mydomain@my.public.ip.removed', '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; skip_imports=1; verbosity=2; exec compile(sys.stdin.read(770), "assembler.py", "exec")\'']
Permission denied (publickey).
c : fatal: failed to establish ssh session (1)
```
Using the [patches](https://github.com/pthrasher/sshuttle/pull/1) I made  off the @pthrasher [fork](https://github.com/pthrasher/sshuttle) it works just fine. In that connection i run ```./sshuttle --dns -vvr myuser@mydomain@my.public.ip.removed 0/0``` without sudo. sshuttle does prompt for sudo, here is the output
```
thshdw-mac-pro:src thshdw$ ./sshuttle --dns -vvr myuser@mydomain@my.public.ip.removed 0/0
Starting sshuttle proxy.
recvmsg socket_ext support enabled.
UDP support requires tproxy; disabling UDP.
Binding redirector: 12300
TCP redirector listening on ('127.0.0.1', 12300).
Binding DNS: 12300
DNS listening on ('127.0.0.1', 12300).
[local sudo] Password: 
```
I then enter my sudo pass and then I see 
```
c : connecting to server...
c : executing: ['ssh', 'myuser@mydomain@my.public.ip.removed, '--', 'P=python2; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; skip_imports=1; verbosity=2; exec compile(sys.stdin.read(770), "assembler.py", "exec")\'']
Authenticated with partial success.
PAM Authentication
Password for myuser@mydomain: 
```
I then enter my password and it connects.

It seems that running the command as sudo fails the public key check. Connecting without sudo works but then no traffic is sent because its not getting the server side ip.

**Comment by seanzxx** [comment]
@thshdw I create a new pull request #5  to fix the sudo issue. 
Feel free to give me feedback. 
Thanks a lot.

**Comment by thshdw** [comment]
@seanzxx Thank you! This is now working for me. 
I suggested a PR https://github.com/seanzxx/sshuttle/pull/1 to your PR https://github.com/sshuttle/sshuttle/pull/5 so we can have some basic anchor support.

**Comment by thshdw** [comment]
@seanzxx I updated my PR with the apple suggested method of closing anchors with -X token
You get the token by running ```sudo pfctl -a com.apple/sshuttle -s Reference```
```
PID      Process Name                 TOKEN                    TIMESTAMP
5191     pfctl                        10051342025653898869     0 days 00:00:07
```
when you close sshuttle you can see that the correct token is used to close this anchor.
```
>> pfctl -X 10051342025653898869
```
If the token is not found then we use this method to close. 
```
pfctl('-dF', 'all')
```
This way systems using pfctl that are not OSX still close and flush rules.

**Comment by seanzxx** [comment]
I updated my PR for following changes:
1. Create rules for anchor 'sshuttle' in main ruleset programatically?
2. Load rules to anchor 'sshuttle' by PIPE, no temporary pf config anymore. 
3. Stop pf only if the pf was started by sshuttle.

**Comment by thshdw** [comment]
Hi @seanzxx see my comments on https://github.com/seanzxx/sshuttle/pull/1 

I think that we should use apples recommended ```pfctl -X token``` method to close anchors in OSX. 

Thanks!

**Comment by seanzxx** [comment]
@thshdw 
I don't to use -E/-X because I didn't see any benefits.
PF might be started by apple firewall. 
```
-> % sudo pfctl -si
No ALTQ support in kernel
ALTQ related functions disabled
Status: Enabled for 0 days 00:05:03           Debug: Urgent

State Table                          Total             Rate
  current entries                        0               
  searches                            1069          356.3/s
  inserts                               70           23.3/s
  removals                              70           23.3/s
Counters
  match                                368          122.7/s
  bad-offset                             0            0.0/s
  fragment                               0            0.0/s
  short                                  0            0.0/s
  normalize                              0            0.0/s
  memory                                 0            0.0/s
  bad-timestamp                          0            0.0/s
  congestion                             0            0.0/s
  ip-option                              0            0.0/s
  proto-cksum                            0            0.0/s
  state-mismatch                         0            0.0/s
  state-insert                           0            0.0/s
  state-limit                            0            0.0/s
  src-limit                              0            0.0/s
  synproxy                               0            0.0/s
  dummynet                               0            0.0/s
```

I told pfctl to load the rules with -E when the PF was already started. 
```
-> % sudo pfctl -a 'com.apple/sshuttle' -f pf.sshuttle.conf -E
pfctl: Use of -f option, could result in flushing of rules
present in the main ruleset added by the system at startup.
See /etc/pf.conf for further details.

No ALTQ support in kernel
ALTQ related functions disabled
pf enabled
Token : 9814169638545055659
```
Because I only enabled the pf rules without shuttle started, the DNS should not work. 
```
-> % ping www.facebook.com                                                                                                                
ping: cannot resolve www.facebook.com: Unknown host                                                                                                            
```

The sshuttle rules cannot be disabled by only -X. 
```
-> % sudo pfctl -X 9814169638545055659
No ALTQ support in kernel
ALTQ related functions disabled
disable request successful. 1 more pf enable reference(s) remaining, pf still enabled.

-> % ping www.facebook.com
ping: cannot resolve www.facebook.com: Unknown host
```

I also have to flush all rules in the anchor 'com.apple/sshuttle'
```
-> % sudo pfctl -a 'com.apple/sshuttle' -F all                                                                                            
No ALTQ support in kernel
ALTQ related functions disabled
rules cleared
nat cleared
dummynet cleared
2 tables deleted.

-> % ping www.facebook.com
PING star.c10r.facebook.com (31.13.77.6): 56 data bytes
64 bytes from 31.13.77.6: icmp_seq=0 ttl=87 time=57.653 ms
64 bytes from 31.13.77.6: icmp_seq=1 ttl=87 time=100.545 ms
^C
--- star.c10r.facebook.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 57.653/79.099/100.545/21.446 ms
```

**Comment by seanzxx** [comment]
If I use the -E/-X, the code is like this:
```
pfctl -a 'com.apple/ssshuttle' -f pf-sshuttle.conf -E
... 
...
token = get_token_from_pf()
pfctl -F all -X token
```

If I use the -e/-d, the code is like this:
```
pf_disabled = get_pf_disabled()
pfctl -a 'com.apple/ssshuttle' -f pf-sshuttle.conf ('-e' if pf_disabled else '')
... 
...
pfctl -F all (-d if pf_disabled else '')
```

**Comment by seanzxx** [comment]
I find the -E/-X useful on OS X because there're other softwares depend on PF. 
I changed my PR to use -E/-X. 
@thshdw thank you very much.

**Comment by thshdw** [comment]
@seanzxx You're Welcome. Thanks for incorporating -E / -X  I think that the only think left would be checking the OS version. In my [suggested PR](https://github.com/thshdw/sshuttle/commit/b4d41c3125b938c4051afc24f3ba85b28eec1362) I do this:
```
	if sys.platform == "darwin":
            pfctl('-a', 'com.apple/sshuttle', '-f', '/etc/pf-sshuttle.conf', '-E')
	else:
	    pfctl('-Ef', pf_config_file)
        os.remove(pf_config_file)
    else:
	token_cmd = shlex.split('sudo pfctl -a com.apple/sshuttle -s Reference')
        token_process = ssubprocess.Popen(token_cmd, stdout=ssubprocess.PIPE).communicate()[0]
        match_token = re.search(r"\s\W\D[0-9]*\b\D\W", token_process)  
        if match_token is not None:
            pfctl_token = match_token.group()	
	    pfctl('-X', pfctl_token.strip())
	else:
	    pfctl('-dF', 'all')
```
I do this because ```-E``` and ```-X``` are OS X specific switches. With non OS X installs that use pfctl we need to use ```-e``` see the OpenBSD [man page for pfctl](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man8/pfctl.8?query=pfctl) 

Also thank you for your contributions and time :smile:

**Comment by seanzxx** [comment]
@thshdw OK, I added -e/-d.

**Comment by thshdw** [comment]
@seanzxx Awesome, thank you!. 

@brianmay When you have a moment could you review @seanzxx latest PR https://github.com/sshuttle/sshuttle/pull/5 He has fixed the sudo issue, removed processing the rule set from files, added proper anchor support for OSX using ```-E``` and ```-X```, added an os check making sure the right anchor commands are called as ```-E``` and ```-X``` are only in OSX

I have been testing these changes and they work very well. Finally sshuttle is Yosemite ready :+1: 

Thank you!

**Pull request merged**
