### PR TITLE
Allow to tunnel into non-ASCII terminals

### PR DESCRIPTION
**Pull request by alanjds**

### CODE REVIEW

**Comment by brianmay** [comment]
Doesn't setting LC_ALL to C ensure that the output of netstat will be ASCII regardless of the default?

**Comment by alanjds** [comment]
You could be right. This patch just "worked for me".

**Comment by vieira** [comment]
I think that the commit 8fad282 solved this. When someone reported a similar issue in April I was able to reproduce and when @brianmay fixed it I tested and indeed the problem no longer occurred.

Just to be sure, I did checkout the commit prior to the fix (1dda9dd) and the problem was:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "assembler.py", line 37, in <module>
  File "sshuttle.server", line 236, in main
  File "sshuttle.server", line 87, in list_routes
  File "sshuttle.server", line 69, in _list_routes
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
```

I then checked out 8fad282 and the current HEAD and both worked fine.

@alanjds Could you give us some more details about the error you got? Could it be that you were running some older version of sshuttle?

**Comment by alanjds** [comment]
Yes, this is the error I got.

Well, I installed via pip. Just now I realize that I should had tested with the master from github. My bad.

Sorry and thanks for investigating.

**Comment by revolunet** [comment]
same from brew channel too

**Comment by brianmay** [comment]
I am guessing brew might be old, this should be fixed in version 0.78.1

**Pull request closed without merging**
