### PR TITLE
Windows client/server support

### LINKED ISSUE #794: Windows support 🤞
I have been using sshuttle for years from my Linux machine, and it works like a magic!  Thanks for this great project!
Recently, I had to switch to Windows for a  project and I wished to use sshuttle  as it was a part of my earlier workflow. 

So I looked into the documentation and found this [https://sshuttle.readthedocs.io/en/stable/windows.html#microsoft-windows](https://sshuttle.readthedocs.io/en/stable/windows.html#microsoft-windows).   
A VM  would be an overkill for just to run sshuttle.   It might be possible to have a similar setup using [WSL](https://docs.microsoft.com/en-us/windows/wsl/) which I haven't looked into yet.
  
 I am thinking  of a native support.  So, I researched a bit on how to achieve native Windows support for sshuttle.  Some options I could found are,

**1.  Method:  windivert**
Use [WinDivert](https://reqrypt.org/windivert.html) for packet capture & modify.     
There is a python wrapper for this library -  https://github.com/ffalcinelli/pydivert 
[mitmproxy](https://github.com/mitmproxy/mitmproxy)  uses pydivert for [it's windows support](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/platform/windows.py#L17)
Windivert requires administrator privilege. 
It's easy to install `pydivert`  library using `pip install pydivert` -  prebuilt artifacts are bundled with PyPi package. 

**2.  Method:  ebpf**
Windows is about to get an official eBPF support - https://github.com/microsoft/ebpf-for-windows
In theory, it's possible to implement a NAT using eBPF.  That's something  https://github.com/cilium/cilium does for implementing CNI for Kubernetes (but only on Linux for now).
ebpf-for-windows requires administrator privilege and additional installation steps.
ebpf-for-windows is not GA yet.  Until then, [ it's not easy to consume it](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/GettingStarted.md#installing-ebpf-for-windows) 
This method might be a good candidate for future, as we could have the same eBPF method working on both Windows and Linux.  

**So I was wondering if maintainers like the idea of supporting Windows with 'windivert' method.   If there is interest, I would love to try to implement it.** 

---
related issues
#32 #448
#742

### PR DESCRIPTION
**Pull request by nom3ad**
This PR contains:

### 1. Client support on Windows using `windivert` method (requires pydivert python package)

**test status**:   
 - Tested on Windows 11 (working as expected on my VM) with Python 3.10
 - Tested for regressions on Linux (None found so far) -  Tried with Python 3.8/3.10/3.11/3/12 on client side and 2.7/3.5/3.6/3.8/3.10/3.11 on server side

**Notes**:  
- sshuttle should be executed from admin shell (Automatic firewall process admin elevation is not available)  - might be doable - need more research.
- TCP/IPv4 supported (UDP and IPv6 are feasible, but not implemented)
-  Based on WindDivert 1.3  (IPv6 impl requires by WinDivert 2 dependency    https://github.com/ffalcinelli/pydivert/pull/57)
-  DNS is not supported (but feasible)
- "--auto-hosts" supported
- subnet filters with port ranges supported
- daemon mode, user/group filtering are not available

For anyone who want to try it out: Please run the following command from an Admin shell (PowerShell/cmd/GitBash).   Requires Python and git installed.

```powershell
PS C:\> pip install "git+https://github.com/nom3ad/sshuttle.git@windows-experimental-support"  -U --force
PS C:\> sshuttle --version
1.2.0
```
Resolves #794 

### 2. Server support on Windows.

- Tested on Windows 11 with Python 3.10. Tested against default OpenSSH server [setup](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration) on Windows. (Default shell being CMD.exe) 
- ~For now, we have to pass `--python=<python-bin>` argument to sshuttle client otherwise it gonna fail with /bin/sh not found error.~
- Based on the server setup, `--remote-shell=<powershell|cmd>` argument should be provided unless a "posix" shell (like git-bash) is configured.  [Update 16/jul/24]
```bash
$ sshuttle -r winuser@windows-server --remote-shell=<powershell|cmd>
```

### 3. Docker container based Test Bed setup that helped me with the development on Windows
- starts multiple docker containers running `sshd`, `nginx` and `ipef3` services using docker compose
-  script files to test connectivity/throughput via sshuttle.

### CODE REVIEW

**Comment by nom3ad** [comment]
@brianmay @skuhl 
Works flows are not yet triggered. Awaiting approval.  Would you like to take a look at the implementation?

I've tried to fit the windivert method on the existing firewall abstraction model.  But still, changes to the rest of the code base were not avoidable due to many Windows quirks.

**Comment by nom3ad** [comment]
Fixed test failures.  Also ensured that python2 compatibility (server side) is not broken by this PR

**Comment by PXNDA-E36** [comment]
Hey man. Just a quick question. Is this the client working on Windows and a Linux server or both WIndows?

**Comment by nom3ad** [comment]
@PXNDA-E36  This is for client side support on Windows.
sshuttle currently do not work with Windows as server target. (but I guess it could be supported, if Windows is running with OpenSSH server.  But I haven't tried it)

**Comment by PXNDA-E36** [comment]
Alright much appreciated!

**Comment by tvarohohlavy** [comment]
Thanks for your work! 

Working fine on:
  Windows 11 Pro 64-bit (10.0, Build 22621) with Python 3.11.4
Syntax I use:
  python -m sshuttle --disable-ipv6 -v --ssh-cmd "ssh -o ServerAliveInterval=60" -r user@host:port subnet1 subnet2 .. subnetN

**Comment by felipecrs** [comment]
This is working very nicely for me too. What is pending for this PR to be merged? I don't think the pending items listed at the top like `--dns` is a blocker to get at least initial support merged.

**Comment by nom3ad** [comment]
Was waiting for others to test it, and it seems working!
@brianmay Would you mind taking a moment to review this PR?   I think I can spend some time this weekend if there are any change requests.

**Comment by fsohi-netgear** [comment]
@nom3ad works with cmd as default shell, does not work with powershell

**Comment by felipecrs** [comment]
Was recently trying this again and I'm running into:

```
fw: setting up.
fw: undoing changes.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\felip\AppData\Local\Programs\Python\Python312\Scripts\sshuttle.exe\__main__.py", line 7, in <module>
  File "C:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\sshuttle\cmdline.py", line 43, in main
    return firewall.main(opt.method, opt.syslog)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\sshuttle\firewall.py", line 343, in main
    method.setup_firewall(
  File "C:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\sshuttle\methods\windivert.py", line 319, in setup_firewall
    proxy_bind_addr = self._get_bind_address_for_port(proxy_port, family)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\felip\AppData\Local\Programs\Python\Python312\Lib\site-packages\sshuttle\methods\windivert.py", line 297, in _get_bind_address_for_port
    for line in subprocess.check_output(["netstat", "-a", "-n", "-p", proto]).decode().splitlines():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 36: invalid start byte
c : fatal: cleanup: ['C:\\Users\\felip\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\sshuttle', '-v', '--method', 'auto', '--firewall'] returned 1
```

**Comment by felipecrs** [comment]
This fixed it:

```
winget uninstall python
rm -rf C:\Users\felip\AppData\Local\Programs\Python
winget install python.python.3.12
python -m pip install --upgrade pip
pip install "git+https://github.com/nom3ad/sshuttle.git@windows-experimental-support" -U --force
pip install pydivert
```

**Comment by nom3ad** [comment]
> @nom3ad works with cmd as default shell, does not work with powershell
@fsohi-netgear Added support for powershell. Now `--remote-shell=powershell/cmd` could be specified in the argument.

**Comment by felipecrs** [comment]
> > @nom3ad works with cmd as default shell, does not work with powershell
> 
> @fsohi-netgear Added support for powershell. Now `--remote-shell=powershell/cmd` could be specified in the argument.

I am trying to understand the need of this. Is this for when the SSH server is Windows?

**Comment by nom3ad** [comment]
@felipecrs  Yes. When SSH server is Windows and configured with cmd or powershell.  I guess if it's setup with something like git-bash, this won't be needed.
If --remote-shell=powershell/cmd provided, `--python=/path/to/exe` workaround could be avoided if python binary located in $PATH enviroment var.

**Comment by felipecrs** [comment]
Got it. Thank you.

By the way I will be trying your latest changes from now on. Will let you know how it goes.

**Comment by nom3ad** [comment]
@brianmay PTAL. Rebased on top of master branch.

**Comment by myname-dyh** [comment]
I tried to connect to my remote server using the same commands as in wsl, but it failed, it works in wsl. I also tried to add --remote-shell=powershell, it still doesn't work. How do I use it correctly?
```
sshuttle 1.2.0
Python 3.12.5
```
Here's error log
```
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:59906->10.35.1.254:53 0B (SYN) SEQ#2839696514 WZ=64240>
fw: ConnTrack: added (TCP 10.35.1.138:59906->10.35.1.254:53 @1725418460:TCP_SYN_SENT) to slot=0 | #ActiveConn=1
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:59907->10.35.1.254:53 0B (SYN) SEQ#999985337 WZ=64240>
fw: [INGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:59906 0B (SYN+ACK) SEQ#4025131664 ACK#2839696515 WZ=65535>
fw: ConnTrack: added (TCP 10.35.1.138:59907->10.35.1.254:53 @1725418460:TCP_SYN_SENT) to slot=1 | #ActiveConn=2
fw: ConnTrack: updated (TCP 10.35.1.138:59906 @1725418460:TCP_ESTABLISHED) from slot=0 | #ActiveConn=2
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.254:53->10.35.1.138:59906 0B (SYN+ACK) SEQ#4025131664 ACK#2839696515 WZ=65535>
fw: [INGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:59907 0B (SYN+ACK) SEQ#3677931568 ACK#999985338 WZ=65535>
```

**Comment by nom3ad** [comment]
> I tried to connect to my remote server using the same commands as in wsl, but it failed, it works in wsl. I also tried to add --remote-shell=powershell, it still doesn't work. How do I use it correctly?
> ```

- Are you connecting to a Windows Server from a Windows Client?
- What's the exact command that being used?
- I Assume you are redirecting entire traffic via shuttle, could you try with a specific subnet/host (and/or port) to see if that works.
- Based on the connection logs, seems like DNS-over-TCP is getting redirected to remote, is that intended?
- Could you please provide more verbose log (-vvv) with full content.

From the attached logs, it seems there are no errors and shuttle is able to redirect the traffic to remote. May be, excluding the DNS traffic would do the trick.

If this is not getting resolved, Please open a new issue further info

**Comment by myname-dyh** [comment]
> > I tried to connect to my remote server using the same commands as in wsl, but it failed, it works in wsl. I also tried to add --remote-shell=powershell, it still doesn't work. How do I use it correctly?
> 
> * Are you connecting to a Windows Server from a Windows Client?
> * What's the exact command that being used?
> * I Assume you are redirecting entire traffic via shuttle, could you try with a specific subnet/host (and/or port) to see if that works.
> * Based on the connection logs, seems like DNS-over-TCP is getting redirected to remote, is that intended?
> * Could you please provide more verbose log (-vvv) with full content.
> 
> From the attached logs, it seems there are no errors and shuttle is able to redirect the traffic to remote. May be, excluding the DNS traffic would do the trick.
> 
> If this is not getting resolved, Please open a new issue further info

I'm connecting from a Windows client to an ubuntu server. 
`sshuttle --dns -r admin@aws-ticket-test-usw2-ec2-java-app-1020.tele.shulex-tech.com 10.0.0.0/8 172.16.0.0/16 172.31.0.0/16 -vvv`
```
The detailed logs are as follows
Starting sshuttle proxy (version 1.2.0).
c : Starting firewall manager with command: ['C:\\Users\\backd\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\sshuttle', '-v', '-v', '-v', '--method', 'auto', '--firewall']
fw: Using inherited stdio for communicating with sshuttle client process
fw: Starting firewall with Python version 3.12.5
fw: Selecting a method automatically...
fw: Method 'windivert' was automatically selected.
fw: ready method name windivert.
c : Failed to read /etc/resolv.conf when looking for DNS servers: No such file or directory
c : Failed to read /run/systemd/resolve/resolv.conf when looking for DNS servers: No such file or directory
c : Using default IPv4 listen address 0.0.0.0
c : IPv6 disabled since it isn't supported by method windivert.
c : Method: windivert
c : IPv4: on
c : IPv6: off (not available with windivert method)
c : UDP : off (not available with windivert method)
c : DNS : off (not available with windivert method)
c : User: off (not available with windivert method)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '10.0.0.0', 8, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '172.16.0.0', 16, 0, 0)
c :   (<AddressFamily.AF_INET: 2>, '172.31.0.0', 16, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '0.0.0.0', 32, 0, 0)
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('0.0.0.0', 12300).
c : TCP redirector listening with <socket.socket fd=760, family=2, type=1, proto=0, laddr=('0.0.0.0', 12300)>.
c : Starting client with Python version 3.12.5
c : Connecting to server...
c : which() found 'ssh' at C:\Windows\System32\OpenSSH\ssh.EXE
c : executing: ['C:\\Windows\\System32\\OpenSSH\\ssh.EXE', 'admin@aws-ticket-test-usw2-ec2-java-app', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; stdin = os.fdopen(0, \'"\'"\'"\'"\'"\'"\'"\'"\'rb\'"\'"\'"\'"\'"\'"\'"\'"\'); exec(compile(stdin.read(1785), \'"\'"\'"\'"\'"\'"\'"\'"\'assembler.py\'"\'"\'"\'"\'"\'"\'"\'"\', \'"\'"\'"\'"\'"\'"\'"\'"\'exec\'"\'"\'"\'"\'"\'"\'"\'"\')); sys.exit(98);\'"\'"\'; exit 97\'']
c : [SocketShim] r=<_io.FileIO name=8 mode='rb' closefd=True> w=<_io.FileIO name=7 mode='wb' closefd=True> | s1=<socket.socket fd=724, family=2, type=1, proto=0, laddr=('127.0.0.1', 62286), raddr=('127.0.0.1', 62287)> s2=<socket.socket fd=632, family=2, type=1, proto=0, laddr=('127.0.0.1', 62287), raddr=('127.0.0.1', 62286)>
c :  > channel=0 cmd=PING len=7 (fullness=0)
 s: Running server on remote host with /usr/bin/python3 (version 3.7.3)
 s: assembling 'sshuttle' (88 bytes)
 s: assembling 'sshuttle.cmdline_options' (85 bytes)
 s: assembling 'sshuttle.helpers' (4143 bytes)
 s: assembling 'sshuttle.ssnet' (5741 bytes)
 s: assembling 'sshuttle.hostwatch' (2530 bytes)
 s: assembling 'sshuttle.server' (4170 bytes)
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 8/8
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=7/0)
c : Connected to server.
c : Waiting: 2 r=[632, 760] w=[632] x=[] (fullness=7/0)
c :   Ready: 2 r=[632] w=[632] x=[]
c : mux read: 23
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
fw: Got subnets: [(2, 8, False, '10.0.0.0', 0, 0), (2, 16, False, '172.16.0.0', 0, 0), (2, 16, False, '172.31.0.0', 0, 0), (2, 32, True, '0.0.0.0', 0, 0)]
fw: Got nslist: []
fw: Got ports: 0,12300,0,0
fw: Got udp: False, user: None, group: None, tmark: 0x01, sshuttle_pid: 28816
fw: setting up.
fw: setting up IPv4.
fw: proxy_port=12300, dnsport=0, nslist=[], family=<AddressFamily.AF_INET: 2>, subnets=[(2, 8, False, '10.0.0.0', 0, 0), (2, 16, False, '172.16.0.0', 0, 0), (2, 16, False, '172.31.0.0', 0, 0), (2, 32, True, '0.0.0.0', 0, 0)], udp=False, user=None, group=None tmark='0x01'
fw: Found non loopback address to connect to proxy: 10.35.1.138
fw: network_config={<IPFamily.IPv4: 2>: {'subnets': [(IPv4Network('10.0.0.0/8'), None, False), (IPv4Network('172.16.0.0/16'), None, False), (IPv4Network('172.31.0.0/16'), None, False), (IPv4Network('0.0.0.0/32'), None, True)], 'nslist': [], 'proxy_addr': (IPv4Address('10.35.1.138'), 12300)}}
fw: ConnTrack: is_owner=True cap=1024 item_sz=43Bshm_name=sshuttle-windivert-28816 shm_sz=66576B
fw: [EGRESS] filter='outbound and tcp and (ip and ((ip.DstAddr>=10.0.0.0 and ip.DstAddr<=10.255.255.255) or (ip.DstAddr>=172.16.0.0 and ip.DstAddr<=172.16.255.255) or (ip.DstAddr>=172.31.0.0 and ip.DstAddr<=172.31.255.255)) and (((ip.DstAddr==0.0.0.0))? false : true) and ((ip.DstAddr==10.35.1.138 and tcp.DstPort==12300)? false : true))'
fw: [INGRESS] filter='outbound and tcp and (ip.SrcAddr==10.35.1.138 and tcp.SrcPort==12300)'
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[632, 760] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[0] w=[] x=[]
 s: mux read: 15
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=14/0)
c :   Ready: 2 r=[632] w=[] x=[]
 s:   Ready: 1 r=[0] w=[] x=[]
 s: mux read: 15
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=0/0)
c : mux read: 15
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[632, 760] w=[] x=[] (fullness=0/0)
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:7680->10.35.1.190:63355 0B (ACK) SEQ#2998750045 ACK#239858540 WZ=4100>
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:7680 0B (RST) SEQ#239858540 WZ=0>
fw: ConnTrack: (TCP src=10.35.1.138:12300) is not found to remove | #ActiveConn=0
fw: [INGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:12300 0B (RST) SEQ#239858540 WZ=0>
fw: ConnTrack: (TCP src=10.35.1.138:12300) is not found to remove | #ActiveConn=0
fw: Unexpected packet: <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:12300 0B (RST) SEQ#239858540 WZ=0>
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:7680->10.35.1.190:63355 0B (ACK) SEQ#2998750045 ACK#239858540 WZ=4100>
fw: [EGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:7680 0B (RST) SEQ#239858540 WZ=0>
fw: ConnTrack: (TCP src=10.35.1.138:12300) is not found to remove | #ActiveConn=0
fw: [INGRESS] <Pkt OUTBOUND 10.35.1.138:12300->10.35.1.138:12300 0B (RST) SEQ#239858540 WZ=0>
fw: ConnTrack: (TCP src=10.35.1.138:12300) is not found to remove | #ActiveConn=0
```

**Comment by nom3ad** [comment]
1. --remote-shell=powershell, argument is wrong to use here as the remote is Ubuntu, not a Windows machine. This argument is only really useful for Windows servers (to select between powershell/CMD/bash.exe)
2. It seems that your client machine's IP is (10.35.1.138) also comes within the forwarded subnet range (10.0.0.0/8) - As I mentioned before, please try with a specific subnet/host. In this case, one that does not include your client machine's network (At least that avoids that machine's IP and gateway/router IP)
3. If excluding the entire 10.0.0.0/8 (Or using a smaller range, that excludes 10.35.1.x) works, then I think we can update some logic in the packet filter to do this automatically.

**Comment by nom3ad** [comment]
> I also tried to change my IP address to 192.168.43.80 that shared from a mobile hotspot.
> sshuttle -l 192.168.43.80 -r admin@aws-ticket-test-usw2-ec2-java-app 10.0.0.0/8 172.16.0.0/16 172.31.0.0/16 -vvv
While connected via mobile hotspot, have you tried accessing the remote resource via IP address?  `curl <internal-ip-of-target-resource>`  (Not using DNS name or public IP) 

Also, as I asked before, try to use a single redirection rule. Something like:
`sshuttle -r admin@aws-ticket-test-usw2-ec2-java-app 172.31.x.y/32 -vvv`
`curl -v 172.31.x.y`   (Pick the correct IP of target resource you want to connect)

Observe and share the debug logs while doing these.

**Comment by myname-dyh** [comment]
I tried using a single rule but that didn't work either, below is one of my test servers, can you show me how I can connect correctly?
`
sshuttle -r root@121.37.178.1 172.17.0.1/32 -vvv
 password: hcss_ecs_d347
`
```
PS C:\Windows\system32> sshuttle -r root@121.37.178.1 172.17.0.1/32 -vvv
Starting sshuttle proxy (version 1.2.0).
c : Starting firewall manager with command: ['C:\\Users\\backd\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\sshuttle', '-v', '-v', '-v', '--method', 'auto', '--firewall']
fw: Using inherited stdio for communicating with sshuttle client process
fw: Starting firewall with Python version 3.12.5
fw: Selecting a method automatically...
fw: Method 'windivert' was automatically selected.
fw: ready method name windivert.
c : Using default IPv4 listen address 0.0.0.0
c : IPv6 disabled since it isn't supported by method windivert.
c : Method: windivert
c : IPv4: on
c : IPv6: off (not available with windivert method)
c : UDP : off (not available with windivert method)
c : DNS : off (not available with windivert method)
c : User: off (not available with windivert method)
c : Subnets to forward through remote host (type, IP, cidr mask width, startPort, endPort):
c :   (<AddressFamily.AF_INET: 2>, '172.17.0.1', 32, 0, 0)
c : Subnets to exclude from forwarding:
c :   (<AddressFamily.AF_INET: 2>, '0.0.0.0', 32, 0, 0)
c : Trying to bind redirector on port 12300
c : TCP redirector listening on ('0.0.0.0', 12300).
c : TCP redirector listening with <socket.socket fd=668, family=2, type=1, proto=0, laddr=('0.0.0.0', 12300)>.
c : Starting client with Python version 3.12.5
c : Connecting to server...
c : which() found 'ssh' at C:\Windows\System32\OpenSSH\ssh.EXE
c : executing: ['C:\\Windows\\System32\\OpenSSH\\ssh.EXE', 'root@121.37.178.1', '--', '/bin/sh -c \'P=python3; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=3; stdin = os.fdopen(0, \'"\'"\'"\'"\'"\'"\'"\'"\'rb\'"\'"\'"\'"\'"\'"\'"\'"\'); exec(compile(stdin.read(1785), \'"\'"\'"\'"\'"\'"\'"\'"\'assembler.py\'"\'"\'"\'"\'"\'"\'"\'"\', \'"\'"\'"\'"\'"\'"\'"\'"\'exec\'"\'"\'"\'"\'"\'"\'"\'"\')); sys.exit(98);\'"\'"\'; exit 97\'']
c : [SocketShim] r=<_io.FileIO name=8 mode='rb' closefd=True> w=<_io.FileIO name=7 mode='wb' closefd=True> | s1=<socket.socket fd=712, family=2, type=1, proto=0, laddr=('127.0.0.1', 56517), raddr=('127.0.0.1', 56518)> s2=<socket.socket fd=700, family=2, type=1, proto=0, laddr=('127.0.0.1', 56518), raddr=('127.0.0.1', 56517)>
c :  > channel=0 cmd=PING len=7 (fullness=0)
 s: Running server on remote host with /usr/bin/python3 (version 3.10.12)
 s: assembling 'sshuttle' (88 bytes)
 s: assembling 'sshuttle.cmdline_options' (85 bytes)
 s: assembling 'sshuttle.helpers' (4143 bytes)
 s: assembling 'sshuttle.ssnet' (5741 bytes)
 s: assembling 'sshuttle.hostwatch' (2530 bytes)
 s: assembling 'sshuttle.server' (4170 bytes)
 s: latency control setting = True
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s: auto-nets:False
 s:  > channel=0 cmd=ROUTES len=0 (fullness=7)
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[1] x=[] (fullness=7/0)
 s:   Ready: 1 r=[] w=[1] x=[]
 s: mux wrote: 8/8
c : Connected to server.
c : Waiting: 2 r=[668, 700] w=[700] x=[] (fullness=7/0)
c :   Ready: 2 r=[700] w=[700] x=[]
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=7/0)
c : mux read: 23
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=0
fw: Got subnets: [(2, 32, False, '172.17.0.1', 0, 0), (2, 32, True, '0.0.0.0', 0, 0)]
fw: Got nslist: []
fw: Got ports: 0,12300,0,0
fw: Got udp: False, user: None, group: None, tmark: 0x01, sshuttle_pid: 2000
fw: setting up.
fw: setting up IPv4.
fw: proxy_port=12300, dnsport=0, nslist=[], family=<AddressFamily.AF_INET: 2>, subnets=[(2, 32, False, '172.17.0.1', 0, 0), (2, 32, True, '0.0.0.0', 0, 0)], udp=False, user=None, group=None tmark='0x01'
fw: Found non loopback address to connect to proxy: 192.168.43.80
fw: network_config={<IPFamily.IPv4: 2>: {'subnets': [(IPv4Network('172.17.0.1/32'), None, False), (IPv4Network('0.0.0.0/32'), None, True)], 'nslist': [], 'proxy_addr': (IPv4Address('192.168.43.80'), 12300)}}
fw: ConnTrack: is_owner=True cap=1024 item_sz=43Bshm_name=sshuttle-windivert-2000 shm_sz=66576B
fw: [EGRESS] filter='outbound and tcp and (ip and ((ip.DstAddr==172.17.0.1)) and (((ip.DstAddr==0.0.0.0))? false : true) and ((ip.DstAddr==192.168.43.80 and tcp.DstPort==12300)? false : true))'
fw: [INGRESS] filter='outbound and tcp and (ip.SrcAddr==192.168.43.80 and tcp.SrcPort==12300)'
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 2 r=[668, 700] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[0] w=[] x=[]
 s: mux read: 15
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=7)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=14/0)
 s:   Ready: 1 r=[0] w=[] x=[]
 s: mux read: 15
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[0] w=[] x=[] (fullness=0/0)
c :   Ready: 2 r=[700] w=[] x=[]
c : mux read: 15
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 2 r=[668, 700] w=[] x=[] (fullness=0/0)
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0
```

**Comment by nom3ad** [comment]
Holy cow! I wouldn't dare to share "root" ssh credentials to strangers over internet. 
I really hope you have shared completely isolated test bed, which you don't care at all if it's pwned. Even if it's the case, I would not put it on public site for any matter.
Please take necessary actions if you did this by mistake. 

Any way, tried sshuttle from windows. It seems working just fine.
image

**Comment by myname-dyh** [comment]
Yes, this is just a simple test server for me. I'm only posting it to make it easier to reproduce the problem, the front log content looks consistent, but the back keeps coming up with `fw: ConnTrack: GC: collected 0 connections | #ActiveConn=0 content`, which is actually causing the traffic to not pass through the tunnel.

**Pull request merged**
