### PR TITLE
fix sudo issue in yosemite

### PR DESCRIPTION
**Pull request by seanzxx**
I moved the pf related codes to firewall process. 
When the client needs to get destination address, it sends command to firewall process.

### CODE REVIEW

**Comment by thshdw** [comment]
@brianmay Awesome! Thank you! :smile:

**Comment by glorat** [comment]
I picked this up for testing on Mac OS 10.10.2

So far so good! Thanks all for the great work

**Comment by uraimo** [comment]
Hi all, i'm testing this too on 10.10.3 and  for now it's working.

Regarding the update to the homebrew formula we talked about in the first PR on Yosemite support, that still points to the unmaintained sshuttle repo, considering that this fix breaks the functionality for pre-yosemite (correct?) i would recommend to generate two release archives (the apenwarr repo is at 0.61, this one has still 0.5x as last archive):

* A 0.7 version before the yosemite fix commits (this and the original repo have diverged significantly with stuff that has been cherry-picked, i would not use 0.6x)

* A 0.whatever after that 0.7 (could be a minor, could be a maintenance release) that contains the yosemite fixes.

That way i could update the formula to pick the right version depending on the osx release, pointing to two different repos would be messy... better keep everything in one place.

**Comment by uraimo** [comment]
Ok, quite easy, someone with write credential just have to create two tags and push them:

    git tag sshuttle-0.70 6121a6dca3e2c8ee33e4bacc591c3f16ce2aa036
    git tag sshuttle-0.71
    git  push  --tags

and then the archives will be generated automatically.

**Comment by brianmay** [comment]
Done. I also added a small patch to 0.71 (2cfc39fac854154b5cbff56713cd3e108c1b29a2) - something i noticed a while back that really didn't look correct.

**Comment by uraimo** [comment]
Thanks Brian, opened a PR on homebrew/homebrew#38581.

**Pull request merged**
