### PR TITLE
Fix/pep8

### PR DESCRIPTION
**Pull request by venthur**
Re-organized imports and fixed all remaining pep8 issues.

### CODE REVIEW

**Comment by brianmay** [comment]
Will this have conflicts with #276? If so, which pull request should I look at first?

**Comment by venthur** [comment]
I'd probably go with the `tests` first, but I'll either way refresh the other patch if needed.

**Comment by venthur** [comment]
There's another change I've made. Instead of having code duplaction in `.travis.yml` and `tox.ini` I'm basically just calling `tox` for the various Pythons from travis and let tox handle all the test running etc.
I also moved the config for pytest into `setup.cfg` and removed the superfluous `--select` which selected stuff that wasn't `--ignore`d anyways by pytest.

**Comment by venthur** [comment]
Done.

**Comment by venthur** [comment]
I refreshed the pull request with the latest changes from `master` -- I also spend some time to wrestle with Codacy that doesn't like to see emtpy `try-except-pass` blocks which you have alot in `sshuttle/firewall.py`

**Comment by brianmay** [comment]
Note that replacing `except:` with `except Exception:` means we won't catch `KeyboardInterrupt`. I can't think why these should matter however. It looks like we use a `finally` clause for cleanup, so this should still happen.

More importantly, github is reporting merge conflicts...

**Comment by venthur** [comment]
Alrighty, I've replaced the bare `Exception`s with `BaseException`s which will capture `KeyboardInterrupt` et al as well. I don't see any merge conflicts with the `master` branch though.

**Comment by brianmay** [comment]
Unfortunately github seems to be convinced that there are merge conflicts. Maybe might have to merge this manually?

**Comment by brianmay** [comment]
Oh, never mind, I think I see what the problem is. Should be able to fix this later today (hopefully).

**Comment by brianmay** [comment]
Thanks for this.

**Pull request merged**
