### PR TITLE
Use flake8 to find Python syntax errors or undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Undefined name '__verbosity__' in assembler.py...
* https://travis-ci.org/sshuttle/sshuttle/jobs/341649202#L440-L447

### CODE REVIEW

**Comment by brianmay** [comment]
Looks like flake8 is not running for Python 2.6. Do we still need to support Python 2.6???

For other Python versions, we get two false warnings. While I understand flake, and tend to agree with it, the fact is it is wrong. Suggestions to deal with this appreciated.

**Comment by cclauss** [comment]
2.6 end of life was five years ago... https://devguide.python.org/#status-of-python-branches

**Comment by brianmay** [comment]
@cclauss: Yes agreed. However see #81.

If you take the oldest still supported version of Redhat, what Python version does it have? I think this may have been the issue previously.

**Comment by cclauss** [comment]
https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Product_life_cycle 45 daze more for RL4

If you __cat ./sshuttle/assembler.py | python2 ./sshuttle/assembler.py__ I believe that it will raise NameError.

**Comment by brianmay** [comment]
What version of Python does RH5 have?

`assember.py` isn't designed to be run standalone line a normal python module. It is a small script that is passed to the server via ssh, with global variables already initialised. See https://github.com/sshuttle/sshuttle/blob/master/sshuttle/ssh.py#L99

**Comment by cclauss** [comment]
https://distrowatch.com/table.php?distribution=redhat Python v2.4.3

**Comment by brianmay** [comment]
I think you will need to either rebase against Master or merge in Master. Otherwise it won't test with the other change.

**Comment by cclauss** [comment]
Done.  It seems to be working.

**Comment by brianmay** [comment]
Merged. Thanks!

**Pull request merged**
