### PR TITLE
Fix/tests

### PR DESCRIPTION
**Pull request by venthur**
I've moved the tests from `sshuttle/tests` into `tests` which is currently the most common approach for python packages. The `conftest.py` has been moved to `tests` as well, making the fixtures available for everything below `tests/`.

### CODE REVIEW

**Comment by brianmay** [comment]
Previously I moved all my tests in all my packages to under the module directory by user request... However I believe this change does make sense.

**Comment by brianmay** [comment]
I believe this change would require a corresponding change to the `MANIFEST.in` to include the tests in the source...

**Comment by venthur** [comment]
Both ways are possible, however, having the test code outside the application code is the most common setup you'll find in most projects. https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code
Regarding the `MANIFEST.in`, this is only for non-code files -- so I believe we could actually **remove** some lines from there.
Running `python setup.py sdist`, I still find the tests in the resulting package.

**Comment by brianmay** [comment]
Is there any documentation that says `MANIFEST.in` is only for non-code files? I believe if entries are missing, they will not get included in the source file.

Anyway, thanks for your contribution. Will merge after allowing some time for a response to the above.

**Comment by venthur** [comment]
Sure, here's some docs for the `MANIFEST.in`. https://docs.python.org/3.6/distutils/sourcedist.html#specifying-the-files-to-distribute

I ran a little test, where I generated a `sdist` with and without the `MANIFEST.in`, and the only file missing in the second `sdist` was the manifest itself.

**Comment by brianmay** [comment]
Hmmm. Wonder if something has changed at some point, I don't recall this behaviour in the past. Anyway, will merge,

**Pull request merged**
