### PR TITLE
Fix parsing of hostnames to allow ssh aliases defined in ssh configs)

### LINKED ISSUE #417: Remotehost parsing of simple hostname or ssh alias throws IndexError
When starting sshuttle with an alias defined in ~/.ssh/config, like the following: `./run -r paua 10.1.2.3/32` or a simple hostname as remotehost, it throws an IndexError while parsing the given remotehost (to find username/password, host and port):

```
[local sudo] Password:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)                                                                                                                                                                                         
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[...]/sshuttle/__main__.py", line 4, in <module>                                                                                                                    
    sys.exit(main())                                                                                                                                                                                              
  File "[...]/sshuttle/sshuttle/cmdline.py", line 102, in main
    opt.sudo_pythonpath)
  File "[...]/sshuttle/sshuttle/client.py", line 800, in main
    seed_hosts, auto_hosts, auto_nets, daemon, to_nameserver)                                                                                                                                                     
  File "[...]/sshuttle/sshuttle/client.py", line 458, in _main
    auto_nets=auto_nets))
  File "[...]/sshuttle/sshuttle/ssh.py", line 108, in connect
    username, password, port, host = parse_hostport(rhostport)                                                                                                                                                    
  File "[...]/sshuttle/sshuttle/ssh.py", line 89, in parse_hostport                                                                                                                  
    host = "{}".format(re.split(r'\s*@', rhostport)[1])                                                                                                                                                           
IndexError: list index out of range   
```

### PR DESCRIPTION
**Pull request by tobigrimm**
This fixes  #417 for me and allows connecting to aliases configured in ssh config as before

### CODE REVIEW

**Comment by tobigrimm** [comment]
Oh, I also tried cleaning up some of the parsing code, but didn't checked the old closed issues yet that introduced the parser as it is before this commit. I'll check my branch if it correctly parses the examples from #401 and #410

**Comment by brianmay** [comment]
@tobigrimm Not sure based on you last message if this is ready to merge or not. Can you please let me know when ready? Thanks

**Comment by brianmay** [comment]
Probably want to see the comments in #412 also if you haven't already.

**Comment by vBlackOut** [comment]
it's possible to login in `ssh host` ? simply on ssh ? I did not know

**Comment by tobigrimm** [comment]
> it's possible to login in `ssh host` ? simply on ssh ? I did not know
> 
> humm but your reuse the same username on your computer Oo weird

For convenience if you have the same user everywhere, e.g. at home/for your personal machines or in a corporate setting with company-wide managed accounts :)

**Comment by tobigrimm** [comment]
> Probably want to see the comments in #412 also if you haven't already.

Didn't get to do it yesterday, I'll check through the comments this afternoon and let you know if I think its mergeable. Sorry for being unclear about this.

**Comment by tobigrimm** [comment]
Discovered a stupid error when parsing IPv6 addresses, but all should be fixed now (famous last words..)

**Comment by tobigrimm** [comment]
As a reference, my testcases:

I added the ssh options to forced authentication with a password:

- SSH will prompt for password:
 
  - `sshuttle -r user@IPv6-Address 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no" `
  - `sshuttle -r user@[IPv6-Address]:22 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r user@IPv4-Address 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no" `
  - `sshuttle -r user@IPv4-Address:22 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r user@hostname 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r user@hostname:22 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  -  `sshuttle -r hostname 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r hostname:22 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`


- Password handled by sshpass:
  - `sshuttle -r user:password@IPv6-Address 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no" `
  - `sshuttle -r user:password@[IPv6-Address]:22 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r user:password@IPv4-Address 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no" `
  - `sshuttle -r user:password@IPv4-Address:22 10.1.2.3/32 -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
   - `sshuttle -r user:password@hostname 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  - `sshuttle -r user:password@hostname:22 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  -  (this will use the current user) `sshuttle -r :password@hostname 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`
  -  (this will use the current user)  `sshuttle -r :password@hostname:22 10.1.2.3/32 -vvv -e "ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"`


- SSH with defined hostalias, as that failed before:
`sshuttle -r hostalias 10.1.2.3/32 -vvv`

I hope I didn't miss anything too obvious :)

**Comment by vBlackOut** [comment]
it's work for me :) thank you so much for find other solution for sshpass Great Job :+1:

**Comment by j8r** [comment]
Can the tests somehow be added in the suite?

**Comment by tobigrimm** [comment]
I'll have a look at the tests and try to implement my test cases, from a first glance it should be possible :)

**Comment by brianmay** [comment]
I think it is important that these changes get merged ASAP, so will do so. However if/when you have test cases, please do feel free to create another PR.

**Pull request merged**
