### PR TITLE
Treat address already in use as a transiet failure

### PR DESCRIPTION
**Pull request by vieira**
Should fix one of the problems described in #106.

Please review. Empirically this works but I am not sure if it's best way to handle the issue.

### CODE REVIEW

**Comment by brianmay** [comment]
Just copying my feedback from #106, to somewhere where it can be found:

Any ideas why it is returning "Address already in use"? Suspect the proposed patch is a work around, it isn't going to solve the root cause.

Normally this error would mean "we cannot bind to this port because it is already in use."

I am wondering if it is due to a previous binding on (b'80.237.22.203', 51413) and the operating system still considers it in use, even after we call the socket.close() method. I could understand this with TCP, seems surprising for UDP however.

Alternatively, maybe something is binding to this port without SO_REUSEADDR???

**Comment by brianmay** [comment]
This was the response from @vieira to my feedback that I will also copy here:

> @brianmay It is a workaround as I don't really know what the root cause is yet. This is unrelated but I also get some read: err was: [Errno 11] Resource temporarily unavailable with some frequency but without any other consequences. Not sure about what those are either. Do you know?
> 
> I will have another look at the bind error, taking your sugge

stions into consideration. Thanks!

**Comment by vieira** [comment]
@brianmay Sorry for the delay. I will look into this today or tomorrow. If it turns out that we are not hitting the same ports we opened before, do you think it is possible we are trying to bind to some port that other app (transmission in this case) is already using?

**Comment by brianmay** [comment]
@vieira Sorry, not sure I understand what you are getting at. Which doesn't mean you are wrong, just that I don't understand.

Looking at the log file of one of the failures I see:

c : doing send from (b'80.237.22.203', 51413) to ('51.254.204.93', 51413)

Based on this it seems likely at some point previously, the client at 51.254.204.93:51413 sent a packet to 80.237.22.203:51413, we intercepted it, got a response, now we are sending the response back to the client.

However, we can't just send the response back to the client using any source IP address, we have to use the same IP address that the initial packet was destined for: 80.237.22.203:51413

For some reason when we bind on this address, it fails saying that it is already in use, and I have no idea why. It is possible it is conflicting (somehow) with the socket we already have to receive the first packet, but that seems unlikely because it worked for the first UDP packet (with different source IP address).

**Comment by vieira** [comment]
@brianmay Thanks for your response. It did clear some things to me.

What I was trying to say is that maybe the address is already in use not because it conflicts with some other socket we have but with a socket other application (in this case transmission) has.

I added some lines to collect every address/port we bind to in tproxy.py, here is the list when sshuttle crahes:
```
c : ---> bind addrs ['91.189.94.4', 123, '8.8.8.8', 53, '8.8.8.8', 53, '8.8.8.8', 53, '8.8.8.8', 53, '8.8.8.8', 53, '8.8.8.8', 53, '31.211.102.129', 63947, '37.4.232.221', 51414, '163.172.158.203', 60603, '31.211.102.129', 63947, '89.234.181.48', 6990, '5.79.67.12', 63942, '192.237.167.131', 51820]
c : ---> trying to bind to srcip: ('37.187.112.154', 51413)
c : ---> dstip is: ('51.254.204.93', 51413)
c : ---> False
c : ---> [Errno 98] Address already in use
```
Notice that this is the first time we bind to port 51413.

Here is a strace of sshuttle until it crashes:
```
8490  bind(5, {sa_family=AF_INET, sin_port=htons(12300), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
8490  bind(7, {sa_family=AF_INET, sin_port=htons(12300), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
8490  bind(8, {sa_family=AF_INET, sin_port=htons(12300), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
8495  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8511  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8512  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8512  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8530  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8532  bind(3, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
8490  bind(9, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(9, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(11, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("91.189.92.151")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
8490  bind(11, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(11, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(11, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("91.189.95.21")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
8490  bind(12, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("8.8.8.8")}, 16) = 0
8490  bind(9, {sa_family=AF_INET, sin_port=htons(42013), sin_addr=inet_addr("86.61.71.149")}, 16) = 0
8490  bind(9, {sa_family=AF_INET, sin_port=htons(51413), sin_addr=inet_addr("62.107.67.67")}, 16) = -1 EADDRINUSE (Address already in use)
```
The only time we try to bind to 51413 it fails with EADDRINUSE.

Here is the strace of transmission that is running at the same time as sshuttle.
```
8536  bind(12, {sa_family=AF_INET, sin_port=htons(51413), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
8536  bind(13, {sa_family=AF_INET6, sin6_port=htons(51413), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
8536  bind(13, {sa_family=AF_INET6, sin6_port=htons(51413), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
8536  bind(14, {sa_family=AF_INET, sin_port=htons(51413), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
8536  bind(17, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
8539  bind(15, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
```
Transmission has a AF_INET socket bind to 51413.

Now, I do not understand, given that transmission did bind to 0.0.0.0:51413, why can't we bind to the more specific 62.107.67.67:51413 when we are using REUSEADDR. Is it possible that REUSEADDR does not work with IP_TRANSPARENT?

**Comment by vieira** [comment]
Hmm, looks like it has nothing to do with IP_TRANSPARENT (tested with and without IP_TRANSPARENT on remote and local IPs respectively) and more to do with Transmission not setting REUSEADDR on its socket. The following two snippets are enough to reproduce:

test1.py
```python
import socket
import time
sender = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sender.bind(('0.0.0.0', 8000))
time.sleep(60)
```

test2.py
```python
import socket
sender = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sender.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sender.bind(('51.254.204.93', 8000))
```

Launching `python test1.py` and then running `python test2.py` will result in the following error:
```
Traceback (most recent call last):
  File "test1.py", line 6, in <module>
    sender.bind(('51.254.204.93', 8000))
OSError: [Errno 98] Address already in use
```

Changing `test1.py` to include the following line works, but is not really an option in practice as we cannot expect that every program will set REUSEADDR.
```
sender.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

I have no idea on how to solve this. 😞 Do you?

**Comment by brianmay** [comment]
Oh, I think I am beginning to understand. So this is when running Transmission on the same box sshuttle is running on, and trying to get sshuttle to intercept.

Is this a UDP only issue? I would assume this would also happen if you changed you test programs for TCP too - right?

**Comment by brianmay** [comment]
Ok, so to me it looks like the problem is that Transmission binds to all IP addresses; it looks like this includes IP addresses that don't actually exist on the host computer and are faked by the transparent socket.

**Comment by brianmay** [comment]
Are you able to change the port that the client (Transport) uses? This might be the best solution.

**Comment by vieira** [comment]
Yes, it's possible to change the "Peer listening port" to something other than the default port (51413) by running `transmission-cli -p <other_port>`.

**Pull request closed without merging**
