### PR TITLE
Support Windows11 As A sshuttle Server

### PR DESCRIPTION
**Pull request by o2v**
#### Overview

This change is to solve malfunctions when Microsoft Windows11 was targeted as a remote ssh server 

It may correspond to the following existing issues:

- https://github.com/sshuttle/sshuttle/issues/496
- https://github.com/sshuttle/sshuttle/issues/980

#### Prerequisites

On Windows which expected to be a ssh server:

- Enable [OpenSSH.Server](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=powershell) up & running
- Install Python (In my case it came via node.js installer)
- Ensure python is executable. (It needs to be specified by one of the sshuttle options --python in client side)
- ~~Place a dependency `fcntl.py` or it's substitute [like this](https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows) to site-packages like `C:\Python312\Lib\site-packages` , `C:\Program Files\Python312\lib\site-packages` (or something like those)~~

On client machine:

- Give option --python at initiating sshuttle. e.g. `--python python`
- In order to examine a python executable on server, try something like `ssh user@server "where python"`. In my case I'd recive "`C:\Python312\python.exe`"

Check above items or else you may encounter errors

####  Cases observed

|Worked?|Client|Server|Misc|
|---|---|---|---|
|Affirmative|Debian|Windows11 ( runs as guest VM based on qemu kvm)|Logged in to VPN on the server|
|Affirmative|Debian|MacOSX|Logged in to VPN on the server. Looks working without regression|

#### Misc

[Out of Scope at this PR] I've been guessing the biggest challenging was [select.select()](https://github.com/sshuttle/sshuttle/blob/master/sshuttle/ssnet.py#L491) which [Windows does not support](https://docs.python.org/3/library/select.html#select.select) in some cases. I was assuming it results "OSError: [WinError 10038] An operation was attempted on something that is not a socket" . However such an error was not reproduced on  this change after all. That's because existing implementation seems not passing any file descriptor on server side. if it reproduces in future, consider [some fix](https://stackoverflow.com/questions/22251809/python-select-select-on-windows)

### CODE REVIEW

**Comment by nom3ad** [comment]
@o2v 
FYI: #918

**Comment by o2v** [comment]
@nom3ad 

> Which shell was configured in your Windows OpenSSH setup

It's Powershell

> Have you tried sshuttle with appropriate --remote-shell=<powershell|cmd>.

I haven't so tried `--remote-shell=cmd`, instead of giving `--python python`, and observied even it works fine

> if python path contains whitespaces

You are right. I could even reproduced such a failure by giving `--python "C:\Program Files\New folder\p y t h o n .lnk"`, while placing such a instance.

Therefore my problem can be solved without this change, but thanks to your suggestion instead

**Comment by brianmay** [comment]
Should this change get reverted then?

**Comment by o2v** [comment]
@brianmay 
I'd say yes.
First I thought space divided python executable path is considered to be an edge case. i
But in giving a second thought, if it was the only path to specify and sshuttle user has no admin previlege on that server, he or she has to ask server admin to resolve that crap or connection fails.
So that's how we want to be friendly for such users isn't it?

**Comment by nom3ad** [comment]
@brianmay.  Please do revert (Or I guess Reset & force push would work as well if you will)

- This change seems to be unnecessary. It tries to solve an already solved problem.
 Also, it will make shuttle to fail when there are white-space/special characters in given python path. Maybe this not common among Linux users. But It's a thing on Windows (etc.: Program Files, Or user home directory)

- @o2v faced the issue because they have PowerShell in OpenSSH server side. If it was Bash(from Msys2,Cygwin,Git etc), it would have been working out of the box.  For  Powershell/CMD , user would have to explicitly tell shuttle.  I see that this should be better documented. I can place a PR for that.
 
- The proposed fix doesn't account  `--remote-shell` argument.  This is the correct way to mention what kind of shell is used in the server. I.e (PowerShell, CMD, "POSIX" shells like bash) - They all have differences in how strings are quoted/escaped.  This is more relevant for windows because the user could configure any of these shells, but for Linux/MacOs it doesn't matter.


@o2v I assume that `--remote-shell` worked for you. If you still had an issue, let's fix it on `--remote-shell` code path.

**Comment by nom3ad** [comment]
@brianmay
Would you mind closing all issues that asked for 'Windows support' as we have merged #918 
A list of such issues are mentioned in that PR's description.

**Comment by o2v** [comment]
@nom3ad 
Your assumption is correct.
Meanwhile `--remote-shell` and how it could help for Windows as a server, should be better documented. That's the only concern.

**Pull request merged**
